### ISSUE TITLE
Design der AuthSeiten optimieren

### ISSUE THREAD

**Issue by lfuelling** [lfuelling/textie-web#2]
Bis jetzt sehen die Seiten aus, wie im [Beispiel](https://github.com/lfuelling/jersey-login). Ich werde ein schöneres, dunkleres Design anwenden.

**Comment by YuleZ** [comment]
@lfuelling wird das Design so lassen, hatter gesagt

**Comment by lfuelling** [comment]
Ich sagte, ich werde es nur ein bisschen ändern.
