### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by lfuelling** [lfuelling/textie-web#5]
Backend zum ändern der Config

**Comment by YuleZ** [comment]
done

**Comment by YuleZ** [comment]
failed

**Comment by YuleZ** [comment]
obwohl das backend theoretisch da ist, das frontend fehlt :D

**Comment by lfuelling** [comment]
Ich verwechselte Backend=Serverlogik mit Backend=FrontendDassManNichtGleichSieht.

**Comment by YuleZ** [comment]
also close :D das Grundgerüst steht :D
