### ISSUE TITLE
Mehrere Savegames

### ISSUE THREAD

**Issue by lfuelling** [lfuelling/textie-web#6]
Ein User soll mehrere Savegames haben und zwischen denen wechseln können

**Comment by YuleZ** [comment]
Wenn man speichert, wird das Savegame zusammen mit der Config gespeichert.
Das heißt man hat nur ein Savegame pro Config, es sei denn man läd dieselbe Config erneut hoch, dann hat man mehrere.

**Comment by YuleZ** [comment]
Beim editieren einer Config wird das dazugehörige savegame gelöscht.

**Comment by lfuelling** [comment]
Also hat jeder User eine Config pro Slot?

**Comment by YuleZ** [comment]
Jeder User hat 4 slots mit platz für ein savegame und eine config

**Comment by lfuelling** [comment]
Jetzt nicht mehr
